name: Debug Practice Pipeline

on:
  workflow_dispatch:

jobs:
  debug-job:
    name: Debug Failed Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Build Docker image
        run: docker build -t debug-practice:latest  .