name: Docker App Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: simple-docker-app

jobs:
  checkout:
    name: 01 - Checkout Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository files
        run: ls -la

      - name: Print repository variable
        run: echo "App environment is ${{ vars.APP_ENV }}"

  docker-verify:
    name: 02 - Verify Docker
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Show Docker version
        run: docker --version
        