name: Docker App Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: simple-docker-app
  IMAGE_TAG: latest

jobs:
  checkout:
    name: 01 - Checkout Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository files
        run: ls -la

  docker-verify:
    name: 02 - Verify Docker
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Show Docker version
        run: docker --version

  build-image:
    name: 03 - Build Docker Image
    runs-on: ubuntu-latest
    needs: docker-verify

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

  run-container:
    name: 04 - Run Docker Container
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image again
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Run Docker container
        run: docker run --rm $IMAGE_NAME:$IMAGE_TAG