name: Failure Practice Pipeline

on:
  workflow_dispatch:

jobs:
  fail-job:
    name: Intentional Failure Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Read README file
        run:  cat README.md 