name: First Manual Pipeline

on:
  workflow_dispatch:

jobs:
  hello:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner operating system
        run: uname -a

      - name: Show current folder
        run: pwd

      - name: List repository files
        run: ls -la

      - name: Print welcome message
        run: echo "Hello Azeez Opeoluwa, this command is running inside the Ubuntu runner"