name: First Manual Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  STUDENT_NAME: Azeez Opeoluwa
  APP_NAME: github-actions-practice
  ENVIRONMENT: dev

jobs:
  hello:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner operating system
        run: uname -a

      - name: Show current folder
        run: pwd

      - name: List repository files
        run: ls -la

      - name: Print variables
        run: |
          echo "Student name: $STUDENT_NAME"
          echo "App name: $APP_NAME"
          echo "Environment: $ENVIRONMENT"

      - name: Print welcome message
        run: echo "Hello $STUDENT_NAME, this command is running inside the Ubuntu runner"